// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GXkc5oC53fLBUSJi-SHg1t3ax7L6vEI',  // SAME API key as admin
    appId: '1:756692214030:web:33548b12bf3512b37d375f',  // User app ID
    messagingSenderId: '756692214030',  // SAME as admin app
    projectId: 'dwarkesh-enterprise-b8f03',  // SAME project ID as admin
    authDomain: 'dwarkesh-enterprise-b8f03.firebaseapp.com',  // SAME auth domain
    storageBucket: 'dwarkesh-enterprise-b8f03.appspot.com',   // SAME storage bucket
    measurementId: 'G-XXXXXXXXXX', // Optional: for analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: 'your-android-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'kichanware',
    storageBucket: 'kichanware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'kichanware',
    storageBucket: 'kichanware.appspot.com',
    iosBundleId: 'com.kichanware.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'kichanware',
    storageBucket: 'kichanware.appspot.com',
    iosBundleId: 'com.kichanware.user',
  );
}
